const { VITE_SERVER_ENDPOINT, VITE_WEBSOCKET_SERVER_ENDPOINT } = import.meta.env;

export const SERVER_ENDPOINT = VITE_SERVER_ENDPOINT;
export const WEBSOCKET_SERVER_ENDPOINT = VITE_WEBSOCKET_SERVER_ENDPOINT;
